services:
  - type: web
    name: sonar-marine-debris-detection
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: MODEL_PATH
        value: best.pt
